spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/dev
    username: dev_user
    password: welkom
    platform: mysql
  jpa:
    hibernate:
      # h2 will use create-drop, mysql we want to use validate
      ddl-auto: validate
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql
