spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/prod
    username: prod_user
    password: welkom
    platform: mysql
  jpa:
    hibernate:
      # h2 will use create-drop, mysql we want to use validate
      ddl-auto: validate
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
